services:
  open-telemetry-trace-service:
    container_name: jaeger_1_35
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    image: jaegertracing/all-in-one:1.35
